add elv-live installer (#175)
enable 
  `npm i -g`
to install `elv-live`, `elv-stream`, `elv-admin` globally in your path (eg, in /opt/homebrew/bin/

diff --git a/elv-admin b/elv-admin
--- a/elv-admin
+++ b/elv-admin
@@ -2,4 +2,14 @@
 
 SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-node $SOURCE_DIR/utilities/EluvioCli.js $* 
+
+if [ -e $SOURCE_DIR/utilities/EluvioCli.js ]
+then
+  node $SOURCE_DIR/utilities/EluvioCli.js $* 2>&1
+elif [ -e $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioCli.js ]
+then
+  node $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioCli.js $* 2>&1
+else
+  echo "(elv-live-js) cannot find utilities/EluvioCli.js" 1>&2
+  exit 1
+fi
