add elv-admin command

diff --git a/elv-admin b/elv-admin
--- a/elv-admin
+++ b/elv-admin
@@ -2,14 +2,30 @@
 
 SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
+USE_V1=false
+ARGS=()
 
-if [ -e $SOURCE_DIR/utilities/EluvioCli.js ]
-then
-  exec node $SOURCE_DIR/utilities/EluvioCli.js "$@" 2>&1
-elif [ -e $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioCli.js ]
-then
-  exec node $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioCli.js "$@" 2>&1
+for arg in "$@"; do
+  if [ "$arg" = "--v1" ]; then
+    USE_V1=true
+  else
+    ARGS+=("$arg")
+  fi
+done
+
+if [ "$USE_V1" = true ]; then
+  CLI_FILE="EluvioCliV1.js"
 else
-  echo "(elv-live-js) cannot find utilities/EluvioCli.js" 1>&2
+  CLI_FILE="EluvioCli.js"
+fi
+
+if [ -e $SOURCE_DIR/utilities/$CLI_FILE ]
+then
+  exec node $SOURCE_DIR/utilities/$CLI_FILE "${ARGS[@]}" 2>&1
+elif [ -e $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/$CLI_FILE ]
+then
+  exec node $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/$CLI_FILE "${ARGS[@]}" 2>&1
+else
+  echo "(elv-live-js) cannot find utilities/$CLI_FILE" 1>&2
   exit 1
 fi
