wip: split to diff files

diff --git a/elv-live b/elv-live
--- a/elv-live
+++ b/elv-live
@@ -2,13 +2,13 @@
 
 SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-if [ -e $SOURCE_DIR/utilities/EluvioLiveCli.js ]
+if [ -e $SOURCE_DIR/utilities/EluvioLiveCli2.js ]
 then
-  exec node $SOURCE_DIR/utilities/EluvioLiveCli.js "$@" 2>&1
-elif [ -e $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioLiveCli.js ]
+  exec node $SOURCE_DIR/utilities/EluvioLiveCli2.js "$@" 2>&1
+elif [ -e $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioLiveCli2.js ]
 then
-  exec node $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioLiveCli.js "$@" 2>&1
+  exec node $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioLiveCli2.js "$@" 2>&1
 else
-  echo "(elv-live-js) cannot find utilities/EluvioLiveCli.js" 1>&2
+  echo "(elv-live-js) cannot find utilities/EluvioLiveCli2.js" 1>&2
   exit 1
 fi
