Cleaned up .sh files and ran shfmt on them

diff --git a/elv-live b/elv-live
--- a/elv-live
+++ b/elv-live
@@ -1,14 +1,12 @@
 #! /usr/bin/env bash
 
-SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+SOURCE_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
 
-if [ -e $SOURCE_DIR/utilities/EluvioLiveCli.js ]
-then
-  exec node $SOURCE_DIR/utilities/EluvioLiveCli.js "$@" 2>&1
-elif [ -e $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioLiveCli.js ]
-then
-  exec node $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioLiveCli.js "$@" 2>&1
+if [ -e "${SOURCE_DIR}/utilities/EluvioLiveCli.js" ]; then
+	exec node "${SOURCE_DIR}/utilities/EluvioLiveCli.js" "$@" 2>&1
+elif [ -e "${SOURCE_DIR}/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioLiveCli.js" ]; then
+	exec node "${SOURCE_DIR}/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioLiveCli.js" "$@" 2>&1
 else
-  echo "(elv-live-js) cannot find utilities/EluvioLiveCli.js" 1>&2
-  exit 1
+	echo "(elv-live-js) cannot find utilities/EluvioLiveCli.js" 1>&2
+	exit 1
 fi
