add v2 separate script

diff --git a/elv-admin b/elv-admin
--- a/elv-admin
+++ b/elv-admin
@@ -2,30 +2,14 @@
 
 SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
-USE_V2=false
-ARGS=()
 
-for arg in "$@"; do
-  if [ "$arg" = "--v2" ]; then
-    USE_V2=true
-  else
-    ARGS+=("$arg")
-  fi
-done
-
-if [ "$USE_V2" = true ]; then
-  CLI_FILE="EluvioCliV2.js"
-else
-  CLI_FILE="EluvioCli.js"
-fi
-
-if [ -e $SOURCE_DIR/utilities/$CLI_FILE ]
+if [ -e $SOURCE_DIR/utilities/EluvioCli.js ]
 then
-  exec node $SOURCE_DIR/utilities/$CLI_FILE "${ARGS[@]}" 2>&1
-elif [ -e $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/$CLI_FILE ]
+  exec node $SOURCE_DIR/utilities/EluvioCli.js "$@" 2>&1
+elif [ -e $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioCli.js ]
 then
-  exec node $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/$CLI_FILE "${ARGS[@]}" 2>&1
+  exec node $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioCli.js "$@" 2>&1
 else
-  echo "(elv-live-js) cannot find utilities/$CLI_FILE" 1>&2
+  echo "(elv-live-js) cannot find utilities/EluvioCli.js" 1>&2
   exit 1
 fi
