update elv-live and elv-admin

diff --git a/elv-admin b/elv-admin
--- a/elv-admin
+++ b/elv-admin
@@ -3,13 +3,13 @@
 SOURCE_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
 
 
-if [ -e $SOURCE_DIR/utilities/EluvioCli2.js ]
+if [ -e $SOURCE_DIR/utilities/EluvioCli.js ]
 then
-  exec node $SOURCE_DIR/utilities/EluvioCli2.js "$@" 2>&1
-elif [ -e $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioCli2.js ]
+  exec node $SOURCE_DIR/utilities/EluvioCli.js "$@" 2>&1
+elif [ -e $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioCli.js ]
 then
-  exec node $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioCli2.js "$@" 2>&1
+  exec node $SOURCE_DIR/../lib/node_modules/@eluvio/elv-live-js/utilities/EluvioCli.js "$@" 2>&1
 else
-  echo "(elv-live-js) cannot find utilities/EluvioCli2.js" 1>&2
+  echo "(elv-live-js) cannot find utilities/EluvioCli.js" 1>&2
   exit 1
 fi
